
@echo off

echo ^:^: The following file is generated by build.bat. DO NOT EDIT. > tmp.bat
copy /b tmp.bat+types.bat tmp2.bat > nul
copy /b tmp2.bat+strings.bat tmp.bat > nul
copy /b tmp.bat+reader.bat tmp2.bat > nul
copy /b tmp2.bat+step1_read_print.bat tmp.bat > nul
copy /b ..\header.bat+tmp.bat ..\step1_read_print.bat > nul
del tmp*.bat > nul
