
@echo off

echo ^:^: The following file is generated by build.bat. DO NOT EDIT. > tmp_comment.bat
copy /b tmp_comment.bat+header.bat+types.bat+strings.bat+reader.bat+printer.bat tmp_base.bat > nul
copy /b tmp_base.bat+_step2_eval.bat step2_eval.bat > nul
copy /b tmp_base.bat+env.bat+_step3_env.bat step3_env.bat > nul
copy /b tmp_base.bat+env.bat+core.bat+_step4_if_fn_do.bat step4_if_fn_do.bat > nul
del tmp*.bat > nul
